import * as vscode from "vscode";
import { parseSource } from "./prtfParser";
import { ParsedSource } from "./prtfModel";
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { regenerateSource } = require("./prtfWriter.js");
// getWebviewHtml is generated by src/buildWebviewTemplate.js at build time
// into out/src/webviewTemplate.js — see that script for why.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { getWebviewHtml } = require("./webviewTemplate.js");

function getNonce(): string {
  let text = "";
  const possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  for (let i = 0; i < 32; i++) text += possible.charAt(Math.floor(Math.random() * possible.length));
  return text;
}

class PrtfDesignerProvider implements vscode.CustomTextEditorProvider {
  public static readonly viewType = "i-rlu.designer";

  constructor(private readonly context: vscode.ExtensionContext) {}

  public static register(context: vscode.ExtensionContext): vscode.Disposable {
    const provider = new PrtfDesignerProvider(context);
    return vscode.window.registerCustomEditorProvider(PrtfDesignerProvider.viewType, provider, {
      webviewOptions: { retainContextWhenHidden: true },
    });
  }

  public async resolveCustomTextEditor(
    document: vscode.TextDocument,
    webviewPanel: vscode.WebviewPanel,
    _token: vscode.CancellationToken
  ): Promise<void> {
    webviewPanel.webview.options = { enableScripts: true };
    webviewPanel.webview.html = getWebviewHtml(getNonce());

    let currentModel: ParsedSource = parseSource(document.getText());

    function currentUom(): string {
      const val = vscode.workspace.getConfiguration("i-rlu").get<string>("unitOfMeasure");
      return val === "cm" ? "cm" : "inch";
    }

    function postModel() {
      webviewPanel.webview.postMessage({ type: "setModel", model: currentModel, uom: currentUom() });
    }

    const changeSub = vscode.workspace.onDidChangeTextDocument((e) => {
      if (e.document.uri.toString() === document.uri.toString()) {
        currentModel = parseSource(document.getText());
        postModel();
      }
    });

    const configSub = vscode.workspace.onDidChangeConfiguration((e) => {
      if (e.affectsConfiguration("i-rlu.unitOfMeasure")) postModel();
    });

    webviewPanel.onDidDispose(() => {
      changeSub.dispose();
      configSub.dispose();
    });

    webviewPanel.webview.onDidReceiveMessage(async (msg) => {
      if (msg.type === "ready") {
        postModel();
        return;
      }
      if (msg.type === "select") {
        // Reserved for a future "properties panel" — no document change yet.
        return;
      }
      if (msg.type === "edit") {
        await this.applyEdit(document, currentModel, msg.edit);
        currentModel = parseSource(document.getText());
        postModel();
      }
    });
  }

  /**
   * Applies a structured edit coming from the webview to the real document.
   * Every edit kind follows the same shape: mutate the in-memory model
   * (model.records[*].fields and the matching entries in model.sequence
   * must be kept in sync, since prtfWriter.regenerateSource walks
   * model.sequence), regenerate source text via prtfWriter, and replace the
   * whole document via a single WorkspaceEdit so VS Code's undo stack sees
   * one coherent change per user action.
   */
  private async applyEdit(document: vscode.TextDocument, model: ParsedSource, edit: any): Promise<void> {
    function findById(id: string): { record: any; entry: any; fieldsIndex: number } | null {
      for (const record of model.records) {
        const fieldsIndex = record.fields.findIndex((f: any) => f.id === id);
        if (fieldsIndex !== -1) return { record, entry: record.fields[fieldsIndex], fieldsIndex };
      }
      return null;
    }

    switch (edit.kind) {
      case "move": {
        const found = findById(edit.id);
        if (!found) return;
        found.entry.line = edit.line;
        found.entry.position = edit.position;
        break;
      }
      case "updateField": {
        const found = findById(edit.id);
        if (!found || found.entry.kind !== "field") return;
        Object.assign(found.entry, {
          name: edit.name,
          length: edit.length,
          dataType: edit.dataType,
          decimalPositions: edit.decimalPositions,
          usage: edit.usage,
          line: edit.line,
          position: edit.position,
        });
        break;
      }
      case "updateConstant": {
        const found = findById(edit.id);
        if (!found || found.entry.kind !== "constant") return;
        Object.assign(found.entry, { literal: edit.literal, line: edit.line, position: edit.position });
        break;
      }
      case "delete": {
        const found = findById(edit.id);
        if (!found) return;
        found.record.fields.splice(found.fieldsIndex, 1);
        const seqIndex = model.sequence.indexOf(found.entry);
        if (seqIndex !== -1) model.sequence.splice(seqIndex, 1);
        break;
      }
      case "setRecordKeyword": {
        // Batch F (and reusable by future keyword-panel batches): adds or
        // replaces a record-level keyword by name. These keywords aren't
        // repeating for this batch's set (DUPLEX/FORCE/OUTBIN/ZFOLD/
        // STAPLE/INVMMAP each appear at most once per record), so "set"
        // replaces any existing entry with the same name rather than
        // appending a duplicate.
        const record = model.records.find((r) => r.name === edit.recordName);
        if (!record) return;
        const raw = edit.params ? edit.name + edit.params : edit.name;
        const existingIndex = record.keywords.findIndex((k: any) => k.name === edit.name);
        const newKeyword = { name: edit.name, params: edit.params || "", raw, sourceLineIndex: -1 };
        if (existingIndex !== -1) record.keywords[existingIndex] = newKeyword;
        else record.keywords.push(newKeyword);
        break;
      }
      case "removeRecordKeyword": {
        const record = model.records.find((r) => r.name === edit.recordName);
        if (!record) return;
        const idx = record.keywords.findIndex((k: any) => k.name === edit.name);
        if (idx !== -1) record.keywords.splice(idx, 1);
        break;
      }
      case "addField":
      case "addConstant": {
        const record = model.records.find((r) => r.name === edit.recordName);
        if (!record) return;
        const newEntry: any =
          edit.kind === "addField"
            ? {
                kind: "field",
                id: "tmp" + Date.now(),
                sourceLineIndex: -1,
                name: edit.name,
                reference: false,
                length: edit.length,
                dataType: edit.dataType,
                decimalPositions: edit.decimalPositions,
                usage: edit.usage,
                line: edit.line,
                position: edit.position,
                conditions: [],
                keywords: [],
              }
            : {
                kind: "constant",
                id: "tmp" + Date.now(),
                sourceLineIndex: -1,
                literal: edit.literal,
                line: edit.line,
                position: edit.position,
                conditions: [],
                keywords: [],
              };
        record.fields.push(newEntry);
        // Insert into the sequence right after this record's last existing
        // field/constant (or right after the record entry itself if it had
        // none), so the new line lands in a sensible place in the source.
        const lastFieldOfRecord = record.fields.length > 1 ? record.fields[record.fields.length - 2] : null;
        const anchor = lastFieldOfRecord || record;
        const anchorIndex = model.sequence.indexOf(anchor);
        model.sequence.splice(anchorIndex === -1 ? model.sequence.length : anchorIndex + 1, 0, newEntry);
        break;
      }
      default:
        return;
    }

    const newText = regenerateSource(model);
    const wsEdit = new vscode.WorkspaceEdit();
    const fullRange = new vscode.Range(
      document.positionAt(0),
      document.positionAt(document.getText().length)
    );
    wsEdit.replace(document.uri, fullRange, newText);
    await vscode.workspace.applyEdit(wsEdit);
  }
}

async function compilePrtf(): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showWarningMessage("I-RLU: open a printer file source member first.");
    return;
  }
  const uri = editor.document.uri;
  try {
    // Delegates to Code for i's "runCommand" API if that extension is
    // installed and the workspace has an active IBM i connection — same
    // integration point I-SDA uses for its "Compile Menu (CRTMNU)" command.
    const codeForI = vscode.extensions.getExtension("halcyontechltd.code-for-ibmi");
    if (!codeForI) {
      vscode.window.showErrorMessage(
        "I-RLU: the Code for IBM i extension is required to compile (CRTPRTF). Install it and connect to your system first."
      );
      return;
    }
    if (!codeForI.isActive) await codeForI.activate();
    const api = codeForI.exports;
    const fileName = uri.path.split("/").pop() || "";
    const memberName = fileName.replace(/\.[^.]+$/, "").toUpperCase();
    const command = `CRTPRTF FILE(&CURLIB/${memberName}) SRCFILE(&CURLIB/QDDSSRC) SRCMBR(${memberName})`;
    await api.runCommand({ command, environment: "ile" });
    vscode.window.showInformationMessage(`I-RLU: submitted CRTPRTF for ${memberName}. Check the Code for IBM i output panel for results.`);
  } catch (err: any) {
    vscode.window.showErrorMessage(`I-RLU: compile failed - ${err?.message || err}`);
  }
}

export function activate(context: vscode.ExtensionContext): void {
  context.subscriptions.push(PrtfDesignerProvider.register(context));
  context.subscriptions.push(
    vscode.commands.registerCommand("i-rlu.openDesigner", async () => {
      const editor = vscode.window.activeTextEditor;
      if (!editor) return;
      await vscode.commands.executeCommand(
        "vscode.openWith",
        editor.document.uri,
        PrtfDesignerProvider.viewType
      );
    })
  );
  context.subscriptions.push(vscode.commands.registerCommand("i-rlu.compilePrtf", compilePrtf));
}

export function deactivate(): void {
  // Nothing to clean up beyond what context.subscriptions already handles.
}
