import * as vscode from "vscode";
import { parseSource } from "./prtfParser";
import { ParsedSource, FieldEntry } from "./prtfModel";
import { WebviewEdit, WebviewMessage } from "./webviewProtocol";
import { findEntryById, applyEditToModel } from "./prtfEdits";
import {
  CompileTarget,
  targetFromMemberUri,
  deriveMemberNameFromFileName,
  validateIbmIObjectName,
  buildCrtprtfCommand,
} from "./prtfCompileTarget";
import { DesignerOpenMode, normalizeDesignerOpenMode } from "./designerOpenMode";
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { regenerateSource, upsertReffldKeyword, applyModificationTracking, buildModTag } = require("./prtfWriter.js");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const PrtfEngine = require("./prtfEngine.js");
// getWebviewHtml is generated by src/buildWebviewTemplate.js at build time
// into out/src/webviewTemplate.js — see that script for why.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { getWebviewHtml } = require("./webviewTemplate.js");

function getNonce(): string {
  let text = "";
  const possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  for (let i = 0; i < 32; i++) text += possible.charAt(Math.floor(Math.random() * possible.length));
  return text;
}

/**
 * Batch X (docs/TASKS.md) — the "Track source modifications" feature's
 * session-scoped tracking state a designer panel applies edits with. Not
 * just a plain boolean/string pair: `enabled`/`tag` are what
 * prtfWriter.js's applyModificationTracking actually reads.
 */
type ModTrackingOptions = { enabled: boolean; tag: string };

/**
 * Reads the two global modification-tracking settings — these are only
 * ever the STARTING values a designer session's own Properties-panel
 * checkbox/tag box initialize from (see resolveCustomTextEditor's own
 * modTrackingEnabled/modTrackingTag session variables below); toggling
 * them in the panel is session-only and never writes back here, mirroring
 * I-SDA's own getModTrackingConfig (src/extension.ts, Task L38).
 */
function getModTrackingConfig(): ModTrackingOptions {
  const config = vscode.workspace.getConfiguration("i-rlu");
  return {
    enabled: !!config.get<boolean>("trackSourceModifications", false),
    tag: buildModTag(config.get<string>("modificationTag", "") || ""),
  };
}

/**
 * Shared choke point for every DDS source edit this designer makes to the
 * real document: computes the fresh source text from `model` via
 * prtfWriter's regenerateSource, wraps the (before, after) pair with
 * modification tracking (a no-op when `modTracking.enabled` is false —
 * see applyModificationTracking's own doc comment in prtfWriter.js), and
 * applies the result as a single WorkspaceEdit so VS Code's undo stack
 * sees one coherent change per user action. Splitting into lines the same
 * way I-SDA's own commitSourceChange does (buildWebviewTemplate.js) —
 * `/\r\n|\r|\n/` — so a CRLF-saved source file's tracking still lines up
 * old/new line-for-line rather than tripping over its own line endings.
 */
async function applyTrackedDocumentEdit(
  document: vscode.TextDocument,
  model: ParsedSource,
  modTracking: ModTrackingOptions
): Promise<void> {
  const oldText = document.getText();
  const newText = regenerateSource(model);
  const finalText = modTracking.enabled
    ? applyModificationTracking(oldText.split(/\r\n|\r|\n/), newText.split(/\r\n|\r|\n/), modTracking).join("\n")
    : newText;

  const wsEdit = new vscode.WorkspaceEdit();
  const fullRange = new vscode.Range(document.positionAt(0), document.positionAt(oldText.length));
  wsEdit.replace(document.uri, fullRange, finalText);
  await vscode.workspace.applyEdit(wsEdit);
}

class PrtfDesignerProvider implements vscode.CustomTextEditorProvider {
  public static readonly viewType = "i-rlu.designer";

  constructor(private readonly context: vscode.ExtensionContext) {}

  public static register(context: vscode.ExtensionContext): vscode.Disposable {
    const provider = new PrtfDesignerProvider(context);
    return vscode.window.registerCustomEditorProvider(PrtfDesignerProvider.viewType, provider, {
      webviewOptions: { retainContextWhenHidden: true },
    });
  }

  public async resolveCustomTextEditor(
    document: vscode.TextDocument,
    webviewPanel: vscode.WebviewPanel,
    _token: vscode.CancellationToken
  ): Promise<void> {
    webviewPanel.webview.options = { enableScripts: true };
    webviewPanel.webview.html = getWebviewHtml(getNonce());

    let currentModel: ParsedSource = parseSource(document.getText());

    function currentUom(): string {
      const val = vscode.workspace.getConfiguration("i-rlu").get<string>("unitOfMeasure");
      return val === "cm" ? "cm" : "inch";
    }

    function postModel() {
      webviewPanel.webview.postMessage({ type: "setModel", model: currentModel, uom: currentUom() });
    }

    // Drives the webview's "IBM i: Connected/Not connected/Not installed"
    // badge and the Resolve/Browse Referenced Field buttons' visibility —
    // same sendCodeForIStatus pattern and timing I-SDA's Task L18 uses:
    // called on 'ready' (badge populated before anything needing a
    // connection is clicked), right after resolveReferencedField/
    // browseReferencedField below (so a just-established or just-dropped
    // connection is reflected without waiting for the next poll), on a
    // cheap poll while the panel is open (catches a connection made/lost
    // from OUTSIDE this panel, e.g. Code for i's own connection tree), and
    // on vscode.extensions.onDidChange (catches Code for i being installed
    // or uninstalled while this panel is already open).
    const sendCodeForIStatus = async () => {
      const status = await getCodeForIStatus();
      webviewPanel.webview.postMessage({ type: "codeForIStatus", installed: status.installed, connected: status.connected });
    };
    const statusPollInterval = setInterval(() => { void sendCodeForIStatus(); }, 10000);
    const extChangeSub = vscode.extensions.onDidChange(() => { void sendCodeForIStatus(); });

    // Batch X — per-panel session state for "Track source modifications".
    // Starts at the global settings' current values; from here on it's
    // owned by the webview's own Properties-panel checkbox/tag box (see
    // the "setModTracking" message handler below) — same session-only-
    // override relationship I-SDA's own equivalent has with its settings.
    let modTrackingEnabled = getModTrackingConfig().enabled;
    let modTrackingTag = getModTrackingConfig().tag;

    // Pushes the global modification-tracking defaults to the webview —
    // once up front (on "ready") and again whenever either setting
    // changes while this panel is still open, so a settings.json edit
    // made mid-session is reflected without needing to reopen the
    // designer. Mirrors I-SDA's own sendModTrackingConfig (Task L38).
    const sendModTrackingConfig = () => {
      const cfg = getModTrackingConfig();
      webviewPanel.webview.postMessage({ type: "modTrackingConfig", enabled: cfg.enabled, tag: cfg.tag });
    };
    const modTrackingConfigSub = vscode.workspace.onDidChangeConfiguration((e) => {
      if (e.affectsConfiguration("i-rlu.trackSourceModifications") || e.affectsConfiguration("i-rlu.modificationTag")) {
        sendModTrackingConfig();
      }
    });

    const changeSub = vscode.workspace.onDidChangeTextDocument((e) => {
      if (e.document.uri.toString() === document.uri.toString()) {
        currentModel = parseSource(document.getText());
        postModel();
      }
    });

    const configSub = vscode.workspace.onDidChangeConfiguration((e) => {
      if (e.affectsConfiguration("i-rlu.unitOfMeasure")) postModel();
    });

    webviewPanel.onDidDispose(() => {
      changeSub.dispose();
      configSub.dispose();
      clearInterval(statusPollInterval);
      extChangeSub.dispose();
      modTrackingConfigSub.dispose();
    });

    webviewPanel.webview.onDidReceiveMessage(async (msg: WebviewMessage) => {
      if (msg.type === "ready") {
        postModel();
        await sendCodeForIStatus();
        sendModTrackingConfig();
        return;
      }
      if (msg.type === "select") {
        // Reserved for a future "properties panel" — no document change yet.
        return;
      }
      if (msg.type === "setModTracking") {
        // Batch X — session-only, no model mutation and no re-render:
        // just updates the values the NEXT edit's applyTrackedDocumentEdit
        // call will read.
        modTrackingEnabled = !!msg.enabled;
        modTrackingTag = buildModTag(msg.tag);
        return;
      }
      if (msg.type === "edit") {
        await this.applyEdit(document, currentModel, msg.edit, { enabled: modTrackingEnabled, tag: modTrackingTag });
        currentModel = parseSource(document.getText());
        postModel();
      }
      if (msg.type === "resolveReferencedField") {
        await handleResolveReferencedField(document, currentModel, msg, { enabled: modTrackingEnabled, tag: modTrackingTag });
        currentModel = parseSource(document.getText());
        postModel();
        await sendCodeForIStatus();
      }
      if (msg.type === "browseReferencedField") {
        await handleBrowseReferencedField(document, currentModel, msg, { enabled: modTrackingEnabled, tag: modTrackingTag });
        currentModel = parseSource(document.getText());
        postModel();
        await sendCodeForIStatus();
      }
    });
  }

  /**
   * Applies a structured edit coming from the webview to the real document.
   * The actual model mutation lives in prtfEdits.applyEditToModel (pure,
   * no vscode dependency, unit tested on its own in test/prtfEdits.test.ts)
   * — this method's job is just: mutate, then hand off to
   * applyTrackedDocumentEdit (Batch X) for the regenerate/track/replace
   * choke point shared with the REF/REFFLD resolution handlers below.
   */
  private async applyEdit(
    document: vscode.TextDocument,
    model: ParsedSource,
    edit: WebviewEdit,
    modTracking: ModTrackingOptions
  ): Promise<void> {
    if (!applyEditToModel(model, edit)) return;
    await applyTrackedDocumentEdit(document, model, modTracking);
  }
}

/**
 * Batch H (docs/TASKS.md), part 2 — field metadata fetched from a live IBM i
 * for one referenced field. `dataType` is the real DDS position-35 type code
 * (not a generic SQL type name — see fetchReferencedFieldAttributes' own
 * comment for why DSPFFD's OUTFILE is used instead of the QSYS2.SYSCOLUMNS
 * SQL catalog for this). Mirrors I-SDA's own ReferencedFieldAttributes shape
 * (src/extension.ts) exactly, since it's the same live-lookup problem.
 */
type ReferencedFieldAttributes = { length: number; dataType: string; decimalPositions: number | null };

/**
 * Interprets one DSPFFD OUTFILE row (QADSPFFD/QWHDRFFD format) into DDS's
 * own length/type/decimals shape. Moved to prtfReferenceField.js (Batch H
 * "remaining" piece) once fetchDatabaseFileFields below needed the same
 * mapping fetchReferencedFieldAttributes already used — see that module's
 * own doc comment for why it lives there now instead of here.
 */
const mapDspffdRowToAttributes = PrtfEngine.mapDspffdRowToAttributes;

/**
 * Resolves Code for i's `code-for-ibmi.runCommand`/`runSQL` API the
 * documented way (`instance.getConnection().runCommand`/`.runSQL`, per
 * codefori.github.io/docs/dev/examples/ and I-SDA's own
 * `getConnectedCodeForIBMi()`) — the ONE place in this file that looks up
 * the Code for i extension, activates it, and resolves its connection.
 *
 * This consolidates what used to be three separate, near-identical copies
 * of the same lookup/activate/getConnection sequence: fetchReferencedFieldAttributes
 * and fetchDatabaseFileFields below each had their own inline copy (paired
 * with their own `vscode.commands.executeCommand("code-for-ibmi.runCommand",
 * ...)` calls), and compilePrtf (further down) originally had a broken
 * fourth variant — `codeForI.exports.runCommand(...)` — which doesn't work
 * at all, since `runCommand` was never a method on the extension's
 * top-level `exports`, only on the connection object
 * `exports.instance.getConnection()` returns once actually connected (that
 * bug meant compiling was broken outright, not just missing a nice picker,
 * until it was first fixed here as part of Batch J). Validates both
 * `runCommand` and `runSQL` are present on the resolved connection, since
 * fetchReferencedFieldAttributes/fetchDatabaseFileFields need runSQL too
 * (compilePrtf itself only ever needed runCommand).
 */
async function getCodeForIConnection(): Promise<
  | {
      runCommand: (info: { command: string; environment: string }) => Promise<{ code: number; stdout: string; stderr: string }>;
      runSQL: (sql: string) => Promise<any[]>;
    }
  | undefined
> {
  const ext = vscode.extensions.getExtension("halcyontechltd.code-for-ibmi");
  if (!ext) return undefined;
  if (!ext.isActive) {
    try {
      await ext.activate();
    } catch {
      // fall through — exports may still be usable, or the check below correctly reports "not connected"
    }
  }
  if (!ext.exports) return undefined;
  const instance = ext.exports.instance;
  const connection = instance && typeof instance.getConnection === "function" ? instance.getConnection() : undefined;
  if (!connection || typeof connection.runCommand !== "function" || typeof connection.runSQL !== "function") return undefined;
  return connection;
}

/**
 * Drives the "IBM i: Connected/Not connected/Not installed" badge in the
 * designer webview and the `i-rlu.codeForIConnected` context key (see
 * activate() below) — mirrors I-SDA's own Task L18 (`getCodeForIStatus` in
 * that project's src/extension.ts) exactly, including WHY it's a thin
 * sibling of getCodeForIConnection() above rather than a reuse of it: that
 * function's callers all want "give me a usable connection or undefined"
 * and don't care why one isn't available, while the badge/context-key need
 * to tell "extension not installed" apart from "installed but not
 * connected" — different, actionable states (install Code for i vs. connect
 * to a system). Cheap to call often: no round trip to the IBM i itself,
 * just an extension-registry lookup and (if already active) a plain
 * in-memory connection-object check — the one exception is the same lazy-
 * activation nudge getCodeForIConnection() already documents, which only
 * ever runs once per extension host session (ext.isActive stays true after
 * the first successful activate()).
 */
async function getCodeForIStatus(): Promise<{ installed: boolean; connected: boolean }> {
  const ext = vscode.extensions.getExtension("halcyontechltd.code-for-ibmi");
  if (!ext) return { installed: false, connected: false };
  if (!ext.isActive) {
    try {
      await ext.activate();
    } catch {
      // fall through — same reasoning as getCodeForIConnection(): exports
      // may still be usable, or the checks below correctly report "not connected"
    }
  }
  if (!ext.exports) return { installed: true, connected: false };
  const instance = ext.exports.instance;
  const connection = instance && typeof instance.getConnection === "function" ? instance.getConnection() : undefined;
  const connected = !!(connection && typeof connection.runCommand === "function" && typeof connection.runSQL === "function");
  return { installed: true, connected };
}

/**
 * Fetches one referenced field's real length/type/decimals from a connected
 * IBM i via Code for IBM i — the network half of "Resolve Referenced
 * Field", kept separate from PrtfEngine.resolveReferenceTarget (which only
 * works out WHERE to look, with no I/O of its own, so it can be unit tested
 * without a live connection). Same DSPFFD OUTFILE approach as I-SDA's own
 * fetchReferencedFieldAttributes (src/extension.ts) — see that function's
 * doc comment for why DSPFFD's OUTFILE is used over the QSYS2.SYSCOLUMNS
 * SQL catalog.
 *
 * Legitimately blocked in an environment without a live/connected IBM i —
 * see docs/TASKS.md Batch H, part 2. The UI shape (part 1) doesn't depend
 * on this ever succeeding.
 */
async function fetchReferencedFieldAttributes(
  target: { fieldName: string; library: string | null; file: string }
): Promise<ReferencedFieldAttributes | { error: string }> {
  const connection = await getCodeForIConnection();
  if (!connection) {
    return { error: "Resolve Referenced Field requires the Code for IBM i extension (halcyontechltd.code-for-ibmi), installed and connected." };
  }

  const qualifiedFile = (target.library ? target.library + "/" : "") + target.file;
  const tempMember = "IRLURFFD";
  const dspffdCmd = `DSPFFD FILE(${qualifiedFile}) OUTPUT(*OUTFILE) OUTFILE(QTEMP/${tempMember}) OUTMBR(*FIRST *REPLACE)`;
  let cmdResult: { code: number; stdout: string; stderr: string };
  try {
    cmdResult = await connection.runCommand({ command: dspffdCmd, environment: "ile" });
  } catch (err) {
    return { error: `DSPFFD failed for ${qualifiedFile}: ${err}` };
  }
  if (cmdResult && typeof cmdResult.code === "number" && cmdResult.code !== 0) {
    return { error: `DSPFFD failed for ${qualifiedFile}: ${cmdResult.stderr || cmdResult.stdout || "unknown error"}` };
  }

  const escapedField = target.fieldName.toUpperCase().replace(/'/g, "''");
  const sql = `SELECT WHFLDT, WHFLDB, WHFLDD, WHFLDP FROM QTEMP.${tempMember} WHERE WHFLDI = '${escapedField}' FETCH FIRST 1 ROW ONLY`;
  let rows: any[];
  try {
    rows = await connection.runSQL(sql);
  } catch (err) {
    return { error: `Could not read field metadata for "${target.fieldName}" in ${qualifiedFile}: ${err}` };
  }
  if (!rows || rows.length === 0) {
    return { error: `Field "${target.fieldName}" was not found in ${qualifiedFile}.` };
  }

  return mapDspffdRowToAttributes(rows[0]);
}

/**
 * One field's metadata as listed from a database file — Batch H
 * "remaining" piece's own result shape, a superset of
 * ReferencedFieldAttributes (adds the field's own name and description
 * text, since unlike fetchReferencedFieldAttributes above this isn't
 * looking up one already-known name, it's discovering every field a file
 * has). Mirrors I-SDA's own DatabaseFileField (src/extension.ts, Task
 * L14) exactly.
 */
type DatabaseFileField = ReferencedFieldAttributes & { name: string; text: string };

/**
 * Batch H (docs/TASKS.md) "remaining" piece — "a real file/library/
 * record-format/field picker (currently direct text entry)". Lists every
 * field in a PF/LF (library/file still typed manually — same as
 * fetchReferencedFieldAttributes above needs them already-known — but the
 * record format and field itself are picked from a live list rather than
 * typed blind), following I-SDA's own fetchDatabaseFileFields
 * (src/extension.ts, Task L14 — "the closest existing pattern", per this
 * batch's own task description) closely: same DSPFFD OUTFILE approach,
 * same activation/connection handling, same field mapping via
 * mapDspffdRowToAttributes. The one difference: I-SDA's own version does
 * the "does this file have more than one record format" grouping inline;
 * here that step is `PrtfEngine.groupDatabaseFileFieldRows`
 * (prtfReferenceField.js) instead, so it's independently unit-testable
 * without a live connection — see that function's own doc comment for
 * why `recordFormat` being omitted can come back as `{formats: [...]}`
 * rather than a field list.
 */
async function fetchDatabaseFileFields(
  library: string | null,
  file: string,
  recordFormat?: string
): Promise<{ fields: DatabaseFileField[]; recordFormat: string } | { formats: string[] } | { error: string }> {
  const connection = await getCodeForIConnection();
  if (!connection) {
    return { error: "Browsing fields requires the Code for IBM i extension (halcyontechltd.code-for-ibmi), installed and connected." };
  }

  const qualifiedFile = (library ? library + "/" : "") + file;
  const tempMember = "IRLUDBFF";
  const dspffdCmd = `DSPFFD FILE(${qualifiedFile}) OUTPUT(*OUTFILE) OUTFILE(QTEMP/${tempMember}) OUTMBR(*FIRST *REPLACE)`;
  let cmdResult: { code: number; stdout: string; stderr: string };
  try {
    cmdResult = await connection.runCommand({ command: dspffdCmd, environment: "ile" });
  } catch (err) {
    return { error: `DSPFFD failed for ${qualifiedFile}: ${err}` };
  }
  if (cmdResult && typeof cmdResult.code === "number" && cmdResult.code !== 0) {
    return { error: `DSPFFD failed for ${qualifiedFile}: ${cmdResult.stderr || cmdResult.stdout || "unknown error"}` };
  }

  // WHNAME is DSPFFD's own record-format-name column — see
  // groupDatabaseFileFieldRows's own doc comment for why it matters.
  const sql = recordFormat
    ? `SELECT WHFLDI, WHFTXT, WHFLDT, WHFLDB, WHFLDD, WHFLDP FROM QTEMP.${tempMember} WHERE WHNAME = '${recordFormat.toUpperCase().replace(/'/g, "''")}' ORDER BY WHFLDO`
    : `SELECT WHNAME, WHFLDI, WHFTXT, WHFLDT, WHFLDB, WHFLDD, WHFLDP FROM QTEMP.${tempMember} ORDER BY WHNAME, WHFLDO`;
  let rows: any[];
  try {
    rows = await connection.runSQL(sql);
  } catch (err) {
    return { error: `Could not read field list for ${qualifiedFile}: ${err}` };
  }

  return PrtfEngine.groupDatabaseFileFieldRows(rows, recordFormat);
}

/**
 * Handles a 'browseReferencedField' message from the designer's webview —
 * the "Browse..." button next to REFFLD's field-name input (Batch H
 * "remaining" piece). Resolves the SAME library/file
 * fetchReferencedFieldAttributes/handleResolveReferencedField would (via
 * PrtfEngine.resolveReferenceTarget, reading the already-saved REF/REFFLD —
 * this deliberately does NOT read whatever's currently typed into the
 * webview's own library/file inputs if the person hasn't hit Save yet, same
 * "trust the document, not an unsaved form" choice
 * handleResolveReferencedField already makes), then walks the picker:
 * fetch the field list, show a QuickPick to disambiguate the record format
 * first if fetchDatabaseFileFields came back ambiguous, then a QuickPick
 * to choose the field itself. On a pick, writes straight to the document
 * via upsertReffldKeyword (same as the "updateField" edit's own REFFLD
 * handling in prtfEdits.ts) rather than posting the choice back to the
 * webview for a separate Save click — one less step, and consistent with
 * how "Resolve Referenced Field" itself already applies immediately.
 */
async function handleBrowseReferencedField(
  document: vscode.TextDocument,
  model: ParsedSource,
  msg: { id: string },
  modTracking: ModTrackingOptions
): Promise<void> {
  const found = findEntryById(model, msg.id);
  if (!found || found.entry.kind !== "field") {
    vscode.window.showErrorMessage("I-RLU: field not found.");
    return;
  }
  const entry: FieldEntry = found.entry;

  const target = PrtfEngine.resolveReferenceTarget(model, found.record, entry);
  if (!target) {
    vscode.window.showInformationMessage(
      "I-RLU: no REF/REFFLD file to browse fields from for this field — set and save a library/file first."
    );
    return;
  }

  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: `I-RLU: Browsing fields in ${target.library ? target.library + "/" : ""}${target.file} via Code for IBM i` },
    async () => {
      let outcome = await fetchDatabaseFileFields(target.library, target.file);
      if ("error" in outcome) {
        vscode.window.showErrorMessage(`I-RLU: ${outcome.error}`);
        return;
      }
      if ("formats" in outcome) {
        const formatChoice = await vscode.window.showQuickPick(outcome.formats, {
          placeHolder: `${target.file} has multiple record formats — pick one to browse its fields`,
        });
        if (!formatChoice) return;
        outcome = await fetchDatabaseFileFields(target.library, target.file, formatChoice);
        if ("error" in outcome) {
          vscode.window.showErrorMessage(`I-RLU: ${outcome.error}`);
          return;
        }
      }
      if (!("fields" in outcome) || outcome.fields.length === 0) {
        vscode.window.showInformationMessage(`I-RLU: no fields found in ${target.library ? target.library + "/" : ""}${target.file}.`);
        return;
      }

      const fieldChoice = await vscode.window.showQuickPick(
        outcome.fields.map((f) => ({
          label: f.name,
          description: f.text || undefined,
          detail: `${f.dataType || "A"}, length ${f.length}${f.decimalPositions ? ", " + f.decimalPositions + " decimals" : ""}`,
          field: f,
        })),
        { placeHolder: `Pick a field from ${target.library ? target.library + "/" : ""}${target.file}` }
      );
      if (!fieldChoice) return;

      entry.keywords = upsertReffldKeyword(entry.keywords, { fieldName: fieldChoice.field.name, library: target.library, file: target.file });
      await applyTrackedDocumentEdit(document, model, modTracking);
      vscode.window.showInformationMessage(`I-RLU: Set REFFLD to ${fieldChoice.field.name}.`);
    }
  );
}

/**
 * Handles a 'resolveReferencedField' message from the designer's webview:
 * re-parses the CURRENT document (not whatever model the webview last had —
 * a network round-trip means the document could have changed underneath
 * this by the time results come back), resolves the target field's real
 * attributes over Code for i, and applies the result as a single
 * WorkspaceEdit. `msg.useReferencedValues` mirrors the "Use referenced
 * values" Y/N toggle from docs/KEYWORD-INVENTORY.md §3: when false, the
 * resolved values are only applied where the field doesn't already have its
 * own length/type/decimals (a one-time default), rather than overwriting
 * values the person already set deliberately.
 */
async function handleResolveReferencedField(
  document: vscode.TextDocument,
  model: ParsedSource,
  msg: { id: string; useReferencedValues?: boolean },
  modTracking: ModTrackingOptions
): Promise<void> {
  const found = findEntryById(model, msg.id);
  if (!found || found.entry.kind !== "field") {
    vscode.window.showErrorMessage("I-RLU: field not found.");
    return;
  }
  // Pulled into its own const, typed as FieldEntry, so the "kind === field"
  // narrowing above survives into the async closure below — TS doesn't
  // carry narrowing of an object property (found.entry.kind) across a
  // function boundary, only of a variable that's never reassigned.
  const entry: FieldEntry = found.entry;

  const target = PrtfEngine.resolveReferenceTarget(model, found.record, entry);
  if (!target) {
    vscode.window.showInformationMessage("I-RLU: no REF/REFFLD file to resolve against for this field.");
    return;
  }

  await vscode.window.withProgress(
    { location: vscode.ProgressLocation.Notification, title: `I-RLU: Resolving ${target.fieldName} from ${target.library ? target.library + "/" : ""}${target.file} via Code for IBM i` },
    async () => {
      const outcome = await fetchReferencedFieldAttributes(target);
      if ("error" in outcome) {
        vscode.window.showErrorMessage(`I-RLU: ${outcome.error}`);
        return;
      }

      const useReferencedValues = msg.useReferencedValues !== false;
      const shouldSet = (current: unknown) => useReferencedValues || current === undefined || current === null;
      if (shouldSet(entry.length)) entry.length = outcome.length;
      if (shouldSet(entry.dataType)) entry.dataType = outcome.dataType || entry.dataType;
      if (shouldSet(entry.decimalPositions)) entry.decimalPositions = outcome.decimalPositions === null ? undefined : outcome.decimalPositions;

      await applyTrackedDocumentEdit(document, model, modTracking);
      vscode.window.showInformationMessage(`I-RLU: Resolved ${target.fieldName} from ${target.library ? target.library + "/" : ""}${target.file}.`);
    }
  );
}

const COMPILE_TARGET_STATE_PREFIX = "i-rlu.compileTarget:";

/**
 * Batch J — prompts for library/source-file/member, one showInputBox each
 * (matching I-SDA's `createRemoteMember` prompt shape — plain inputs with
 * placeholder defaults, not a live library/member browser, since Code for
 * i doesn't expose an API for listing libraries/members that this project
 * has confirmed). Returns undefined if the person cancels at any step.
 */
async function promptForCompileTarget(defaultMemberName: string): Promise<CompileTarget | undefined> {
  const library = await vscode.window.showInputBox({
    prompt: "Library for the compiled printer file and its source (blank uses CRTPRTF's own default: *CURLIB for the object, *LIBL to search for the source)",
    placeHolder: "blank = *CURLIB / *LIBL",
    validateInput: (v) => (v.trim() ? validateIbmIObjectName(v) : undefined),
  });
  if (library === undefined) return undefined;

  const sourceFile = await vscode.window.showInputBox({
    prompt: "Source physical file containing this member's DDS",
    placeHolder: "QDDSSRC",
    value: "QDDSSRC",
    validateInput: validateIbmIObjectName,
  });
  if (sourceFile === undefined) return undefined;

  const memberName = await vscode.window.showInputBox({
    prompt: "Source member name",
    value: defaultMemberName,
    validateInput: validateIbmIObjectName,
  });
  if (memberName === undefined) return undefined;

  return { library: library.trim(), sourceFile: sourceFile.trim(), memberName: memberName.trim() };
}

/**
 * Batch J — resolves where CRTPRTF should compile from, in priority order:
 * 1. A `member:` URI (opened directly from Code for i) names the exact
 *    library/source-file/member itself — used as-is, no prompt, and NOT
 *    cached (re-deriving it is free and always accurate; caching a stale
 *    copy would only risk drifting from the real URI if the file were ever
 *    reopened from a different location).
 * 2. A previously prompted-and-cached target for this exact document
 *    (`context.workspaceState`, keyed by the document's URI string) — so
 *    repeat compiles of the same local file don't re-prompt every time.
 * 3. Prompt (`promptForCompileTarget`), then cache the result for next time.
 * Returns undefined if the person cancels the prompt.
 */
async function resolveCompileTarget(context: vscode.ExtensionContext, document: vscode.TextDocument, forcePrompt: boolean): Promise<CompileTarget | undefined> {
  const memberTarget = targetFromMemberUri(document.uri.scheme, document.uri.path);
  if (memberTarget) return memberTarget;

  const stateKey = COMPILE_TARGET_STATE_PREFIX + document.uri.toString();
  if (!forcePrompt) {
    const cached = context.workspaceState.get<CompileTarget>(stateKey);
    if (cached) return cached;
  }

  const fileName = document.uri.path.split("/").pop() || "";
  const target = await promptForCompileTarget(deriveMemberNameFromFileName(fileName));
  if (!target) return undefined;
  await context.workspaceState.update(stateKey, target);
  return target;
}

async function compilePrtf(context: vscode.ExtensionContext): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showWarningMessage("I-RLU: open a printer file source member first.");
    return;
  }
  const document = editor.document;

  // CRTPRTF has no stream-file source equivalent — confirmed against IBM's
  // own CRTPRTF parameter reference (ibm.com/docs/ssw_ibm_i_72/cl/crtprtf.htm):
  // SRCFILE/SRCMBR (a database source member) are the only source options;
  // TOSTMF is the command's *output* stream-file target, unrelated. Rather
  // than silently guessing a library/file for an IFS-opened source (which
  // has neither), this is surfaced as the genuine IBM i command limitation
  // it is.
  if (document.uri.scheme === "streamfile") {
    vscode.window.showErrorMessage(
      "I-RLU: CRTPRTF can't compile directly from an IFS stream file — it has no SRCSTMF-equivalent parameter (verified against IBM's CRTPRTF reference). Copy this source into a database source member (e.g. via Code for i) and compile that instead."
    );
    return;
  }

  try {
    const connection = await getCodeForIConnection();
    if (!connection) {
      vscode.window.showErrorMessage(
        "I-RLU: the Code for IBM i extension is required to compile (CRTPRTF). Install it and connect to your system first."
      );
      return;
    }

    const target = await resolveCompileTarget(context, document, false);
    if (!target) return; // person cancelled the prompt

    if (document.isDirty) await document.save();

    const command = buildCrtprtfCommand(target);
    const result = await connection.runCommand({ command, environment: "ile" });
    if (result && typeof result.code === "number" && result.code !== 0) {
      vscode.window.showErrorMessage(`I-RLU: CRTPRTF failed - ${(result.stderr || result.stdout || "unknown error").trim()}`);
      return;
    }
    vscode.window.showInformationMessage(`I-RLU: submitted CRTPRTF for ${target.memberName}. Check the Code for IBM i output panel for results.`);
  } catch (err: any) {
    vscode.window.showErrorMessage(`I-RLU: compile failed - ${err?.message || err}`);
  }
}

/**
 * Batch J — lets the person change (or set for the first time) the cached
 * compile target for the active document, without waiting for the next
 * compile to prompt. A no-op with an explanatory message for `member:`
 * URIs, since there's nothing to override there — the URI itself is
 * already the exact, correct target (see resolveCompileTarget).
 */
async function setCompileTarget(context: vscode.ExtensionContext): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showWarningMessage("I-RLU: open a printer file source member first.");
    return;
  }
  const document = editor.document;
  if (document.uri.scheme === "member") {
    vscode.window.showInformationMessage(
      "I-RLU: this file was opened directly from an IBM i member, so its library/source file/member are already exact — nothing to set."
    );
    return;
  }
  const target = await resolveCompileTarget(context, document, true);
  if (target) {
    vscode.window.showInformationMessage(
      `I-RLU: compile target set to ${target.library || "*CURLIB/*LIBL"}/${target.sourceFile}(${target.memberName}). It'll be reused for future compiles of this file.`
    );
  }
}



/**
 * Sets the `i-rlu.codeForIConnected` context key package.json's
 * commandPalette `when` clause for i-rlu.compilePrtf reads (see
 * package.json), so the compile command drops out of the Command Palette
 * the moment there's no live connection to compile against, rather than
 * staying listed and failing with an error message once clicked. This is
 * the global-command-visibility half of the same "don't offer an action
 * that's guaranteed to fail while disconnected" fix I-SDA's Task L18 makes
 * for its own webview-button Compile/Add-fields actions — adapted to
 * i-rlu.compilePrtf specifically because it's reached via Command
 * Palette/keybinding rather than a webview button, so there's no per-panel
 * badge to hide it from; a single global poll (rather than one per open
 * designer panel) is what a context key needs, since it's shared VS
 * Code-wide state, not per-webview state.
 */
function watchCodeForIConnectedContext(context: vscode.ExtensionContext): void {
  const update = async () => {
    const status = await getCodeForIStatus();
    await vscode.commands.executeCommand("setContext", "i-rlu.codeForIConnected", status.connected);
  };
  void update();
  const poll = setInterval(() => { void update(); }, 10000);
  const extChangeSub = vscode.extensions.onDidChange(() => { void update(); });
  context.subscriptions.push({ dispose: () => clearInterval(poll) }, extChangeSub);
}

/**
 * Batch W — where "I-RLU: Open Report Designer" (and opening a
 * .pf/.prtf/.rlu file via the editor selector) puts the designer.
 * The actual value-normalization decision lives in designerOpenMode.ts
 * (unit-testable there without a real VS Code host); this just reads
 * the setting and defers to it.
 */
function getDesignerOpenMode(): DesignerOpenMode {
  return normalizeDesignerOpenMode(
    vscode.workspace.getConfiguration("i-rlu").get<string>("designerOpenColumn")
  );
}

/**
 * Opens the visual designer via the standard "open with a specific
 * custom editor" command (same `vscode.openWith` approach the previous,
 * column-less version of this command already used — see
 * PrtfDesignerProvider for why a real CustomTextEditorProvider is used
 * at all rather than a plain WebviewPanel). Where exactly it opens is
 * governed by getDesignerOpenMode() above. Mirrors I-SDA's identical
 * openInDesigner (see that project's src/extension.ts).
 */
async function openInDesigner(uri: vscode.Uri, viewType: string): Promise<void> {
  const mode = getDesignerOpenMode();
  const column = mode === "beside" ? vscode.ViewColumn.Beside : vscode.ViewColumn.Active;
  await vscode.commands.executeCommand("vscode.openWith", uri, viewType, column);
  if (mode === "newWindow") {
    // Operates on whichever editor is currently active - the openWith
    // above just made the designer webview that editor, so this pops IT
    // out (not the original source tab, which is left behind in the
    // original window). Identical to I-SDA's own openInDesigner, see
    // that function's comment for the same reasoning.
    await vscode.commands.executeCommand("workbench.action.moveEditorToNewWindow");
  }
}

export function activate(context: vscode.ExtensionContext): void {
  context.subscriptions.push(PrtfDesignerProvider.register(context));
  watchCodeForIConnectedContext(context);
  context.subscriptions.push(
    // Accepts an optional `uri` — VS Code passes the right-clicked
    // resource's URI as the first argument when this command is invoked
    // from a context/title menu (see package.json's "menus" contribution
    // below), which is NOT necessarily the active text editor's document
    // (e.g. right-clicking an unopened .prtf file in the Explorer). Falls
    // back to the active editor only when invoked with no argument at all
    // (Command Palette). Previously this always read
    // vscode.window.activeTextEditor and ignored any argument, so it did
    // nothing when the target file wasn't already the focused editor —
    // and there was no menu contribution wiring it into a right-click
    // menu in the first place (see package.json), so in practice it was
    // reachable only via the Command Palette.
    //
    // Batch W: previously always opened in vscode.ViewColumn.Active with
    // no way to configure that — now delegates to openInDesigner(), which
    // reads the i-rlu.designerOpenColumn setting.
    vscode.commands.registerCommand("i-rlu.openDesigner", async (uri?: vscode.Uri) => {
      const target = uri ?? vscode.window.activeTextEditor?.document.uri;
      if (!target) return;
      await openInDesigner(target, PrtfDesignerProvider.viewType);
    })
  );
  context.subscriptions.push(vscode.commands.registerCommand("i-rlu.compilePrtf", () => compilePrtf(context)));
  context.subscriptions.push(vscode.commands.registerCommand("i-rlu.setCompileTarget", () => setCompileTarget(context)));
}

export function deactivate(): void {
  // Nothing to clean up beyond what context.subscriptions already handles.
}
