import * as vscode from "vscode";
import { parseSource } from "./prtfParser";
import { ParsedSource } from "./prtfModel";
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { regenerateSource } = require("./prtfWriter.js");
// getWebviewHtml is generated by src/buildWebviewTemplate.js at build time
// into out/src/webviewTemplate.js — see that script for why.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { getWebviewHtml } = require("./webviewTemplate.js");

function getNonce(): string {
  let text = "";
  const possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  for (let i = 0; i < 32; i++) text += possible.charAt(Math.floor(Math.random() * possible.length));
  return text;
}

class PrtfDesignerProvider implements vscode.CustomTextEditorProvider {
  public static readonly viewType = "i-rlu.designer";

  constructor(private readonly context: vscode.ExtensionContext) {}

  public static register(context: vscode.ExtensionContext): vscode.Disposable {
    const provider = new PrtfDesignerProvider(context);
    return vscode.window.registerCustomEditorProvider(PrtfDesignerProvider.viewType, provider, {
      webviewOptions: { retainContextWhenHidden: true },
    });
  }

  public async resolveCustomTextEditor(
    document: vscode.TextDocument,
    webviewPanel: vscode.WebviewPanel,
    _token: vscode.CancellationToken
  ): Promise<void> {
    webviewPanel.webview.options = { enableScripts: true };
    webviewPanel.webview.html = getWebviewHtml(getNonce());

    let currentModel: ParsedSource = parseSource(document.getText());

    function postModel() {
      webviewPanel.webview.postMessage({ type: "setModel", model: currentModel });
    }

    const changeSub = vscode.workspace.onDidChangeTextDocument((e) => {
      if (e.document.uri.toString() === document.uri.toString()) {
        currentModel = parseSource(document.getText());
        postModel();
      }
    });

    webviewPanel.onDidDispose(() => {
      changeSub.dispose();
    });

    webviewPanel.webview.onDidReceiveMessage(async (msg) => {
      if (msg.type === "ready") {
        postModel();
        return;
      }
      if (msg.type === "select") {
        // Reserved for a future "properties panel" — no document change yet.
        return;
      }
      if (msg.type === "edit") {
        await this.applyEdit(document, currentModel, msg.edit);
        currentModel = parseSource(document.getText());
        postModel();
      }
    });
  }

  /**
   * Applies a structured edit coming from the webview to the real document.
   * v1 supports moving a field/constant to a new line/position (drag &
   * drop in the preview); further edit kinds (resize, add field, add
   * constant, edit keyword, delete) follow the same pattern: mutate the
   * in-memory model, regenerate source text via prtfWriter, and replace the
   * whole document via a single WorkspaceEdit so VS Code's undo stack sees
   * one coherent change.
   */
  private async applyEdit(document: vscode.TextDocument, model: ParsedSource, edit: any): Promise<void> {
    if (edit.kind === "move") {
      const record = model.records.find((r) => r.name === edit.recordName);
      if (!record) return;
      const target = record.fields.find((f: any) => {
        if (f.kind === "field") return f.name === edit.name && f.line === edit.line && f.position === edit.position;
        return f.literal === edit.text && f.line === edit.line && f.position === edit.position;
      }) as any;
      if (!target) return;
      target.line = edit.newLine;
      target.position = edit.newPosition;
    } else {
      return;
    }

    const newText = regenerateSource(model);
    const wsEdit = new vscode.WorkspaceEdit();
    const fullRange = new vscode.Range(
      document.positionAt(0),
      document.positionAt(document.getText().length)
    );
    wsEdit.replace(document.uri, fullRange, newText);
    await vscode.workspace.applyEdit(wsEdit);
  }
}

async function compilePrtf(): Promise<void> {
  const editor = vscode.window.activeTextEditor;
  if (!editor) {
    vscode.window.showWarningMessage("I-RLU: open a printer file source member first.");
    return;
  }
  const uri = editor.document.uri;
  try {
    // Delegates to Code for i's "runCommand" API if that extension is
    // installed and the workspace has an active IBM i connection — same
    // integration point I-SDA uses for its "Compile Menu (CRTMNU)" command.
    const codeForI = vscode.extensions.getExtension("halcyontechltd.code-for-ibmi");
    if (!codeForI) {
      vscode.window.showErrorMessage(
        "I-RLU: the Code for IBM i extension is required to compile (CRTPRTF). Install it and connect to your system first."
      );
      return;
    }
    if (!codeForI.isActive) await codeForI.activate();
    const api = codeForI.exports;
    const fileName = uri.path.split("/").pop() || "";
    const memberName = fileName.replace(/\.[^.]+$/, "").toUpperCase();
    const command = `CRTPRTF FILE(&CURLIB/${memberName}) SRCFILE(&CURLIB/QDDSSRC) SRCMBR(${memberName})`;
    await api.runCommand({ command, environment: "ile" });
    vscode.window.showInformationMessage(`I-RLU: submitted CRTPRTF for ${memberName}. Check the Code for IBM i output panel for results.`);
  } catch (err: any) {
    vscode.window.showErrorMessage(`I-RLU: compile failed - ${err?.message || err}`);
  }
}

export function activate(context: vscode.ExtensionContext): void {
  context.subscriptions.push(PrtfDesignerProvider.register(context));
  context.subscriptions.push(
    vscode.commands.registerCommand("i-rlu.openDesigner", async () => {
      const editor = vscode.window.activeTextEditor;
      if (!editor) return;
      await vscode.commands.executeCommand(
        "vscode.openWith",
        editor.document.uri,
        PrtfDesignerProvider.viewType
      );
    })
  );
  context.subscriptions.push(vscode.commands.registerCommand("i-rlu.compilePrtf", compilePrtf));
}

export function deactivate(): void {
  // Nothing to clean up beyond what context.subscriptions already handles.
}
